#ifndef CUSTOM_CULL_INPUT_INCLUDED
#define CUSTOM_CULL_INPUT_INCLUDED

#define INPUT_PROP(name) UNITY_ACCESS_INSTANCED_PROP(UnityPerMaterial, name)

UNITY_INSTANCING_BUFFER_START(UnityPerMaterial) //CBUFFER_START(UnityPerMaterial)
    UNITY_DEFINE_INSTANCED_PROP(float, _ZWrite)
UNITY_INSTANCING_BUFFER_END(UnityPerMaterial) //CBUFFER_END

#endif